### ISSUE TITLE
用户名和密码

### ISSUE THREAD

**Issue by Giant-Li** [iranee/qnap-gocron#1]
已按照提示打开了MariDB5，但在MariDB5安装过程中只要求设置了根密码，并没有创建新用户。但在app节点设置中要求填写用户名和密码。请问应该如何创建符合要求的用户名和密码。谢谢！

**Comment by cikichen** [comment]
一样，现在新版本和以前不一样了，我猜可能要自己去安装三方的Mysql

**Comment by iranee** [comment]
回来修复下这个问题

**Comment by iranee** [comment]
> 一样，现在新版本和以前不一样了，我猜可能要自己去安装三方的Mysql

现在已经更新了，可以选择数据库货值直接全新安装！

**Comment by iranee** [comment]
> 已按照提示打开了MariDB5，但在MariDB5安装过程中只要求设置了根密码，并没有创建新用户。但在app节点设置中要求填写用户名和密码。请问应该如何创建符合要求的用户名和密码。谢谢！

现在已经更新了，可以选择数据库货值直接全新安装！
